#!/usr/bin/env python
"""
| File: px4_multi_world_iris_fixedcam.isaac.py
| Derived from px4_multi_world_iris_gimbal3.isaac.py (Marcelo Jacinto, BSD-3-Clause,
| Copyright (c) 2023). Everything not concerning the camera is carried over unchanged.
| Description: Pegasus multi-vehicle world where a selected subset of vehicles carries the
| REAL INTERCEPTOR's sensor — a fisheye lens on a rigid, non-gimballed mount — instead of the
| stabilised pinhole camera. MAS ticket 055.

WHAT IS DIFFERENT FROM THE GIMBAL3 LAUNCHER
Only the camera. Physics, collision filtering, the boot label, the action graphs, the PX4
backends and the vehicle layout are byte-for-byte the same, and `isaac_sim_aggressive` is
unaffected because this is a separate file.

Vehicles in FIXED_CAMERA_VEHICLES get:
  * a 1280x960 render at f = fx = 444.7622 px, fisheye (fTheta) projection;
  * `sub_zoom: False`, because the interceptor has no zoom hardware and because
    MonocularCamera.set_zoom would rebuild the focal length as mean(fx, fy);
  * their gimbal joints held at a constant pose by `gimbal_stabilizer/fixed_mount_publisher`
    on the ROS side (not started here).
Every other camera vehicle keeps exactly today's stabilised pinhole camera.

WHY 1280x960 FOR A 1280x720 CAMERA  (ticket 055 D1, option B)
The real lens has NON-SQUARE pixels: fy/fx = 0.7487, a 4:3 sensor squeezed to 16:9 by the
Argus ISP. Isaac's fTheta model is radial in PIXELS, so fx == fy is structural — the API
enforces it independently (`get_vertical_aperture` derives itself from the resolution aspect
ratio, camera.py:1136-1143). Rendering 1280x720 at f = fx would throw away 14.33 deg of
vertical half-FoV per side. So this launcher renders the UNSQUEEZED 4:3 frame with square
pixels, and `sim_camera_relay` performs the same 0.75 vertical squeeze the real ISP does.
That lands fy at 333.57 against the measured 332.98 (+0.18%).

CONSEQUENCE: the `camera_info` this process publishes is correct for the 1280x960 frame it
renders and WRONG for the 1280x720 frame the consumers see. `sim_camera_relay` republishes it.
Nothing downstream of the relay should ever subscribe to /px4_N/camera/color/camera_info.

WHY THE POLYNOMIAL IS NOT `set_kannala_brandt_properties`  (ticket 055 F1)
Isaac has a one-line helper for exactly this distortion model. It fits the fTheta polynomial
using sample points generated by `point_to_theta` (camera.py:53), which treats the grid as
IDEAL PINHOLE pixels — so for this lens it never samples beyond 58.97 deg while the image runs
to 92 deg, and the outer third of the image radius becomes degree-4 extrapolation. Measured
error of the resulting render law: max 3.5 deg, rms 0.62 deg. Ticket 054 exists to remove a
0.76 deg bearing error. The coefficients below are instead fitted over the TRUE angular range
by `mas/src/doc/active/tickets/055-.../probe_fisheye_ftheta.py`, which is also where every
number in this docstring comes from. Re-run it if the render resolution ever changes; only the
distortion coefficients D are resolution-independent.
"""

# Imports to start Isaac Sim from this script
import argparse
import carb
from isaacsim import SimulationApp

parser = argparse.ArgumentParser()
parser.add_argument("--headless", action="store_true", default=False, help="Run in headless mode")
args, _ = parser.parse_known_args()

# Start Isaac Sim's simulation environment
# Note: this simulation app must be instantiated right after the SimulationApp import, otherwise the simulator will crash
# as this is the object that will load all the extensions and load the actual simulator.
simulation_app = SimulationApp({"headless": args.headless})

# -----------------------------------
# The actual script should start here
# -----------------------------------
import omni.timeline
from omni.isaac.core.world import World

# Import the Pegasus API for simulating drones
from pegasus.simulator.params import ROBOTS, SIMULATION_ENVIRONMENTS
from pegasus.simulator.logic.graphical_sensors.monocular_camera import MonocularCamera
from pegasus.simulator.logic.state import State
from pegasus.simulator.logic.backends.px4_mavlink_backend import PX4MavlinkBackend, PX4MavlinkBackendConfig
from pegasus.simulator.logic.backends.ros2_backend import ROS2Backend
from pegasus.simulator.logic.vehicles.multirotor import Multirotor, MultirotorConfig
from pegasus.simulator.logic.interface.pegasus_interface import PegasusInterface
# Auxiliary scipy and numpy modules
import os.path
from scipy.spatial.transform import Rotation
import numpy as np

import asyncio
import carb
import omni.ext
import omni.graph.core as og
import isaacsim.ros2.bridge as bridge

class PegasusApp:
    """
    A Template class that serves as an example on how to build a simple Isaac Sim standalone App.
    """

    def __init__(self):
        """
        Method that initializes the PegasusApp and is used to setup the simulation environment.
        """

        # Acquire the timeline that will be used to start/stop the simulation
        self.timeline = omni.timeline.get_timeline_interface()

        # Start the Pegasus Interface
        self.pg = PegasusInterface()

        # Acquire the World, .i.e, the singleton that controls that is a one stop shop for setting up physics,
        # spawning asset primitives, etc.
        self.pg._world = World(**self.pg._world_settings)
        self.world = self.pg.world

        # Launch one of the worlds provided by NVIDIA
        self.pg.load_environment(SIMULATION_ENVIRONMENTS["Plane with Light"])

        # Load the Flight aesthetic scene (Y-up USD, rotated to Z-up)
        # self.load_flight_scene(
        #     usd_path="/home/usrg/IsaacPX4/world/Flight/Flight_original.usd",
        #     scale=0.001,
        #     offset=(0.0, 0.0, 0.0),
        # )

        self.world_offset_x, self.world_offset_y, self.world_offset_z = 0,0,0
        # self.world_offset_x = 0.0
        # self.world_offset_y = 0.0
        # self.world_offset_z = 0.0
        # self.world_offset_x = -606344.799574
        # self.world_offset_y = -1586.657862
        # self.world_offset_z = 1395514.256701
        # self.world.reset()
        asyncio.ensure_future(self.create_simulation_time_graph())
        self.create_landmarks()

        # ── GIMBALLED camera (unchanged from px4_multi_world_iris_gimbal3.isaac.py) ──
        # Applies to every camera vehicle NOT in FIXED_CAMERA_VEHICLES.
        #
        # Camera resolution preset (mirrors /home/usrg/mas/src/tmux/drone.tmuxp.yaml
        # and simdrone*.tmuxp.yaml). Override per-launch with `CAMERA_RES=low|mid|high`.
        # Lens is the same across presets — smaller resolutions are sensor crops of
        # the 1920×1080 reference: fx,fy held constant from calibration; cx,cy = w/2, h/2.
        #   low  →  640× 360,  YOLO engine dronecop9-2-384x640
        #   mid  →  960× 540,  YOLO engine dronecop9-2-544x960
        #   high → 1920×1080,  YOLO engine dronecop9-2-1088x1920
        _camera_res = os.environ.get("CAMERA_RES", "high")
        self._camera_res = _camera_res   # kept for the boot label (see write_boot_label)
        if _camera_res == "low":
            self._cam_width, self._cam_height = 640, 360
        elif _camera_res == "mid":
            self._cam_width, self._cam_height = 960, 540
        elif _camera_res == "high":
            self._cam_width, self._cam_height = 1920, 1080
        else:
            raise ValueError(f"unknown CAMERA_RES={_camera_res} (use low|mid|high)")

        # Intrinsics from 2026-04-17/1x calibration (SIYI A8 mini, 1x zoom, 1920×1080):
        #   /home/usrg/mas/datasets/camera_calibration/2026-04-17/1x/intrinsics_summary.json
        # Same-lens assumption → fx, fy constant across resolution presets; cx, cy snap
        # to image center.
        _fx_cal = 1053.044591
        _fy_cal = 1052.905959
        self._cam_matrix = [[_fx_cal, 0, self._cam_width / 2],
                            [0, _fy_cal, self._cam_height / 2],
                            [0, 0, 1]]
        print(f"[PegasusApp] CAMERA_RES={_camera_res}  {self._cam_width}x{self._cam_height}  "
              f"fx={_fx_cal:.2f} fy={_fy_cal:.2f} cx={self._cam_width/2:.1f} cy={self._cam_height/2:.1f}")

        # Derived USD camera parameters — same lens → focal_length constant; aperture
        # scales with resolution so rendered fx_px = focal*width/h_aperture = _fx_cal.
        # Value matches iris_ma6 training env (iris_ma_env6_test_cfg.py): focal_length=11.493,
        # horizontal_aperture=20.955 at 1920×1080 → fx_px = 11.493*1920/20.955 = 1053.04.
        self._cam_focal_length = 11.493  # mm (matches iris_ma6 training PinholeCameraCfg)
        self._cam_h_aperture = self._cam_focal_length * self._cam_width / _fx_cal
        self._cam_v_aperture = self._cam_focal_length * self._cam_height / _fy_cal

        # ── FIXED fisheye camera — the real interceptor (MAS ticket 055) ──────────────
        # Ground truth: cuas_ws/src/nvargus_camera_ros2/config/camera_info_260723_1280x720.yaml
        # (Kalibr pinhole-equidistant, 2026-07-16). fx 444.7622, fy 332.9809, cx 634.6102,
        # cy 359.1967, D = the four KB4 coefficients below. HFoV 157.5 deg, VFoV 119.4 deg.
        #
        # Rendered at 1280x960 with SQUARE pixels at f = fx; sim_camera_relay applies the
        # 0.75 vertical squeeze the Argus ISP applies, recovering fy = 333.57 (+0.18% vs
        # measured). See the module docstring for why this cannot be rendered at 720 directly.
        self._fixed_cam_width, self._fixed_cam_height = 1280, 960
        self._fixed_fx = 444.7621764198695
        self._fixed_d = [0.0435758044787322, -0.01211534975904146,
                         0.008929336243582754, -0.00340237623151779]

        # The principal point is FORCED to the image centre, not set to the measured
        # (634.61, 359.20). `read_camera_info` publishes cx = width/2, cy = height/2
        # unconditionally (camera_info_utils.py:95-96), so authoring the true offset would
        # make the render and the published camera_info disagree by 5.4 px ≈ 0.69 deg. A
        # centred camera that ACCURATELY DESCRIBES ITSELF is worth more than an off-centre
        # one that lies: the consumer unprojects with the published camera_info, so the
        # bearing stays exact. Ticket 055 D6 [3].
        self._fixed_cx = self._fixed_cam_width / 2.0
        self._fixed_cy = self._fixed_cam_height / 2.0

        # fTheta polynomial: theta[rad] = A + B*r + C*r^2 + D*r^3 + E*r^4, r in PIXELS from
        # (fthetaCx, fthetaCy). Fitted over r in [0, 760.6] — the KB4 model's own validity
        # limit (theta_d <= 1.7101), NOT the 800 px frame corner. That range choice is
        # load-bearing: fitting out to the corner spends the degree-4 budget on the region
        # where theta(r) has a vertical tangent and pushes the horizontal-edge error from
        # -0.003 deg to -0.44 deg. Residual over the real pixel grid: rms 0.310 deg,
        # median 0.251, p99 0.919. Produced by probe_fisheye_ftheta.py §Q5 — regenerate
        # there rather than hand-editing if anything about the frame changes.
        self._fixed_ftheta_poly = [1.12544758e-02, 1.87798392e-03, 2.67144608e-06,
                                   -7.06664666e-09, 5.41137316e-12]
        self._fixed_ftheta_max_fov = 199.43   # deg, full angle at r = 760.6 px

        # Isaac's fTheta render law ignores focalLength/aperture, but `read_camera_info`
        # builds the published K from them (camera_info_utils.py:93-94) — so the aperture is
        # what puts fx on the wire. Two independent authoring paths for one quantity; both
        # must say 444.7622. HORIZONTAL ONLY: set_vertical_aperture() would rewrite
        # horizontalAperture behind us (camera.py:1149-1153).
        self._fixed_h_aperture = (self._cam_focal_length * self._fixed_cam_width
                                  / self._fixed_fx)   # 33.0762 mm

        # `mas_bearing_loc/camera_model.py:37` routes KB4 on
        # EQUIDISTANT_MODELS = ("equidistant", "fisheye"). Isaac's own KB4 helper writes
        # "kannalaBrandt", which matches NEITHER — the consumer would fall back to a plain
        # pinhole unprojection silently, with the coefficients present and ignored. This
        # string is passed verbatim into CameraInfo.distortion_model, so it must be the one
        # the consumer knows. Ticket 055 F3.
        self._fixed_distortion_model = "equidistant"

        self.namespace = "px4_"
        self.vehicles = []
        self._vehicle_by_id = {}   # MAS ticket 055 — see vehicle_factory
        # RAL ticket 021 coop_2obs: NUM_VEHICLES=4 adds px4_4 (second flown observer,
        # same camera+gimbal factory). Default 3 keeps every existing session unchanged.
        num_vehicles = int(os.environ.get("NUM_VEHICLES", "3"))
        print(f"[PegasusApp] NUM_VEHICLES={num_vehicles}")

        # RAL ticket 019 revisit2 W0f — CAMERA_VEHICLES: which vehicle ids get a camera.
        # The wall clock of a sweep is set by Isaac RENDERING camera sensors, not by ROS-side
        # fusion CPU, and this factory attaches a 1920x1080 @ 25 Hz MonocularCamera with
        # pub_graphical_sensors:True to EVERY vehicle — including ones whose session starts
        # no camera/YOLO window. In the coop_1obs layout px4_3 (the TARGET) is rendered and
        # published for NO consumer (nothing in `mas` subscribes /px4_3/camera/color/*), so
        # excluding it drops the rendered camera count 3 -> 2, a third off the dominant cost.
        # Default = ALL ids, so every pre-existing session is byte-for-byte unchanged.
        #   CAMERA_VEHICLES="1,2"   -> only px4_1 and px4_2 carry cameras
        # Deliver it via the tmuxp `environment:` block or `tmux setenv -g` and read back with
        # `tmux show-environment -g`: `VAR=... tmuxp load` is silently dropped whenever a tmux
        # server exists, and on this box an idle `keepalive` session keeps one alive always.
        _cam_env = os.environ.get("CAMERA_VEHICLES", "").strip()
        if _cam_env:
            self._camera_ids = {int(x) for x in _cam_env.split(",") if x.strip()}
        else:
            self._camera_ids = set(range(1, num_vehicles + 1))
        print(f"[PegasusApp] CAMERA_VEHICLES={sorted(self._camera_ids)} "
              f"({len(self._camera_ids)} of {num_vehicles} vehicles rendered)")

        # MAS ticket 055 D2 — FIXED_CAMERA_VEHICLES: which of the CAMERA_VEHICLES carry the
        # interceptor's fisheye on a rigid mount instead of the stabilised pinhole camera.
        # The session is deliberately MIXED: an interceptor with the real sensor can fly
        # against targets/observers that keep today's gimbal.
        #   unset/empty          -> every camera vehicle is fixed-fisheye
        #   FIXED_CAMERA_VEHICLES="1"  -> only px4_1; the rest keep the gimballed pinhole
        #   FIXED_CAMERA_VEHICLES="-"  -> none (explicitly: this launcher behaves as gimbal3)
        # Delivery trap, same as CAMERA_VEHICLES above: `VAR=... tmuxp load` is silently
        # dropped whenever a tmux server exists, and an idle `keepalive` session keeps one
        # alive on this box permanently. Pass it via the tmuxp `environment:` block or
        # `tmux setenv -g`, and read back with `tmux show-environment -g`.
        #
        # THE ROS SIDE MUST AGREE. A vehicle listed here needs
        # `gimbal_stabilizer/fixed_mount_publisher` holding its joints; one NOT listed needs
        # `los_rate_controller`. Getting that backwards is silent and looks like a tracking
        # bug rather than a config bug — fisheye intrinsics on a gimbal being swung by a LOS
        # controller, or a rigid mount still wearing the 1053 px pinhole. So the selection is
        # written into the boot label (write_boot_label) and `fixed_mount_publisher` reads it
        # back and refuses to start if its own namespace is absent. Fail-closed, same posture
        # as the collision filter below.
        _fixed_env = os.environ.get("FIXED_CAMERA_VEHICLES", "").strip()
        self._fixed_camera_env_raw = _fixed_env
        if _fixed_env == "-":
            self._fixed_camera_ids = set()
        elif _fixed_env:
            self._fixed_camera_ids = {int(x) for x in _fixed_env.split(",") if x.strip()}
        else:
            self._fixed_camera_ids = set(self._camera_ids)

        _orphans = self._fixed_camera_ids - self._camera_ids
        if _orphans:
            raise ValueError(
                "FIXED_CAMERA_VEHICLES=%r selects vehicle(s) %s that carry no camera at all "
                "(CAMERA_VEHICLES=%s). A fixed MOUNT without a camera renders nothing and "
                "publishes nothing, so this is a configuration mistake rather than a valid "
                "layout — refusing to boot [MAS ticket 055 D2]."
                % (_fixed_env, sorted(_orphans), sorted(self._camera_ids)))

        print(f"[PegasusApp] FIXED_CAMERA_VEHICLES={sorted(self._fixed_camera_ids)} "
              f"(fisheye, rigid mount) | gimballed pinhole: "
              f"{sorted(self._camera_ids - self._fixed_camera_ids)}")

        for i in range(num_vehicles):
            self.vehicle_factory(i+1, gap_x_axis=1.0)

        # RAL ticket 055 S21 — DISABLE_VEHICLE_COLLISION: stop vehicles colliding with
        # EACH OTHER (ground collision is untouched).
        #
        # WHY. The engagement harness runs every trial to TRUE closest-point-of-approach
        # and deliberately "never terminates on a radius crossing", so min_range is an
        # uncensored CPA that stays scorable at any kill radius
        # (mas experiment_conductor.py:430). An interceptor accurate enough to reach a
        # sub-0.2 m CPA therefore flies INTO the target airframe (~0.5 m across). On the
        # RAL 055 E56 DGL cohort that is exactly what happened: trial A-0 hit a 0.104 m
        # CPA, the collision cost the target PX4 its attitude/accel-bias estimate
        # ("Failsafe activated" -> "mc_pos_control: Failsafe: blind land"), and it came to
        # rest INVERTED (roll 178.7 deg) on the ground. Nothing recovers that from inside a
        # running stack: preflight then rejects arming (High Accelerometer Bias, Attitude
        # failure), and the conductor's _reposition FLIES vehicles to the IC rather than
        # teleporting, so a downed vehicle can never settle. Every later trial then
        # measured range-to-corpse (121.88 m) and both boots aborted 1-valid-of-16.
        # Uncensored CPA and physical contact are the same property; this filter keeps the
        # metric and drops the contact.
        #
        # DEFAULT ON as of 2026-08-08 (user decision: the remaining cohort runs filtered,
        # and an opt-IN is something an operator can forget). Until then the default was
        # OFF and the filter was delivered per-boot via `tmux setenv -g`; no tmuxp file
        # ever set it, so a forgotten setenv silently bought back the E56 failure mode.
        #   DISABLE_VEHICLE_COLLISION unset or =1  -> px4_* do not collide with px4_* (default)
        #   DISABLE_VEHICLE_COLLISION=0            -> EXPLICIT OPT-OUT, collision-enabled physics
        # Any other value raises rather than picking a regime silently (as CAMERA_RES does).
        #
        # COMPARABILITY. This flips the physics default, so this launcher is no longer
        # byte-for-byte equivalent to pre-2026-08-08 boots. Every cohort acquired before
        # this commit — RAL 055 E56/E57 and everything earlier — flew collision-ENABLED;
        # E58/E59 flew filtered. Reproducing an older cohort means setting
        # DISABLE_VEHICLE_COLLISION=0 explicitly. See RAL 055 CONSUMER_MANIFEST.md §5.
        #
        # Whichever way it is set, deliver it via the tmuxp `environment:` block or
        # `tmux setenv -g` and read back with `tmux show-environment -g`: `VAR=... tmuxp
        # load` is silently dropped whenever a tmux server exists (same trap as
        # CAMERA_VEHICLES above). That trap is why the opt-out must not be the quiet path.
        # Empty counts as unset (as CAMERA_VEHICLES treats it): the tmuxp files pass this
        # inline as `DISABLE_VEHICLE_COLLISION=${DISABLE_VEHICLE_COLLISION}`, which expands
        # to empty if the `environment:` block ever fails to reach the pane. Falling to the
        # safe default beats aborting the boot, and write_boot_label records the raw value
        # either way, so an empty expansion can never mis-label a cohort.
        _nocollide_raw = os.environ.get("DISABLE_VEHICLE_COLLISION", "").strip()
        _nocollide_env = _nocollide_raw or "1"
        if _nocollide_env not in ("0", "1"):
            raise ValueError(
                "unknown DISABLE_VEHICLE_COLLISION=%r (use 0|1; unset or empty means 1, the "
                "default since 2026-08-08) — refusing to guess a collision regime"
                % _nocollide_raw)
        if _nocollide_env == "1":
            _collision_group = self.disable_vehicle_vehicle_collision(num_vehicles)
        else:
            _collision_group = None
            print("[PegasusApp] *** DISABLE_VEHICLE_COLLISION=0 — EXPLICIT OPT-OUT: "
                  "vehicle-vehicle collision is ON (pre-2026-08-08 physics). An interceptor "
                  "reaching a sub-0.5 m CPA can down a vehicle and invalidate the rest of "
                  "the cohort — see RAL ticket 055 E56. ***")

        # The machine-readable half of the boot witness (RAL ticket 055 §4 follow-up).
        self.write_boot_label(num_vehicles, _nocollide_raw, _collision_group)

        # Reset the simulation environment so that all articulations (aka robots) are initialized
        self.world.reset()

        # Apply camera prim properties after world.reset() (render products exist now)
        # focus_distance and clipping_range match iris_ma6 training env (iris_ma_env6_test_cfg.py).
        #
        # ORDERING IS LOAD-BEARING (MAS ticket 055 r_research.md §7). This must run after
        # world.reset() so the render products exist, and BEFORE the first camera frame
        # reaches ros2_backend — `add_monocular_camera_writter` calls read_camera_info() once
        # and freezes k/p into the CameraInfo writer, so a property set afterwards changes the
        # render without changing what is published. The 100-tick suppression at the top of
        # MonocularCamera.update gives the margin; timeline.play() has not been called yet.
        f_stop = 1.8
        focus_distance = 400.0  # matches training PinholeCameraCfg.focus_distance
        for vehicle_id, vehicle in self._vehicle_by_id.items():
            fixed = vehicle_id in self._fixed_camera_ids
            for sensor in vehicle._graphical_sensors:
                if fixed:
                    self.author_fisheye_camera(sensor._camera, vehicle_id,
                                               f_stop, focus_distance)
                else:
                    sensor._camera.set_focal_length(self._cam_focal_length / 10.0)     # mm → cm
                    sensor._camera.set_focus_distance(focus_distance)
                    sensor._camera.set_lens_aperture(f_stop * 100.0)
                    sensor._camera.set_horizontal_aperture(self._cam_h_aperture / 10.0) # mm → cm
                    sensor._camera.set_vertical_aperture(self._cam_v_aperture / 10.0)
                    sensor._camera.set_clipping_range(0.1, 1.0e5)

        # Auxiliar variable for the timeline callback example
        self.stop_sim = False

    def author_fisheye_camera(self, camera, vehicle_id: int, f_stop: float,
                              focus_distance: float):
        """Author the interceptor's fisheye lens onto one camera prim (MAS ticket 055).

        Deliberately does NOT use `Camera.set_kannala_brandt_properties`, which exists for
        exactly this distortion model. That helper fits the fTheta polynomial from sample
        points generated by `point_to_theta` (camera.py:53) — ideal-pinhole pixels — so for a
        157 deg lens it never samples past 58.97 deg while the image reaches 92 deg, leaving
        the outer third of the image radius as degree-4 extrapolation worth up to 3.5 deg of
        rendered bearing error. The coefficients here were fitted over the true angular range
        instead (probe_fisheye_ftheta.py §Q3/§Q5) and go in through the same lower-level call
        the helper itself ends at.

        Fail-closed, like `disable_vehicle_vehicle_collision`: every authored attribute is
        read back. A lens that silently failed to apply would produce a session that looks
        right, flies for an hour and yields bearings from the wrong camera — which is the
        whole failure class this ticket exists to prevent.
        """
        from pxr import Sdf

        # 1. Projection type FIRST — every set_fisheye_* call raises without it
        #    (camera.py:1251, :1291, :1400). Verified immediately rather than at the readback
        #    below, because if it did not take, step 3 throws Isaac's own bare
        #    Exception("fisheye projection type is not set") first — which names neither the
        #    vehicle nor where to look.
        camera.set_projection_type("fisheyePolynomial")
        _got_type = camera.get_projection_type()
        if "fisheye" not in (_got_type or ""):
            raise RuntimeError(
                "px4_%d: cameraProjectionType is %r after asking for 'fisheyePolynomial' — "
                "the prim rejected the projection type, so no fisheye property can be "
                "authored at all. Refusing to boot [MAS ticket 055]."
                % (vehicle_id, _got_type))

        # 2. The pinhole-side properties. These do NOT drive the fTheta render, but
        #    read_camera_info builds the published K from focalLength/horizontalAperture
        #    (camera_info_utils.py:93-94), so this is what puts fx on the wire.
        #    HORIZONTAL ONLY — set_vertical_aperture would rewrite horizontalAperture
        #    behind us (camera.py:1149-1153).
        camera.set_focal_length(self._cam_focal_length / 10.0)          # mm → cm
        camera.set_focus_distance(focus_distance)
        camera.set_lens_aperture(f_stop * 100.0)
        camera.set_horizontal_aperture(self._fixed_h_aperture / 10.0)   # mm → cm
        camera.set_clipping_range(0.1, 1.0e5)

        # 3. The render law itself.
        camera.set_fisheye_polynomial_properties(
            nominal_width=self._fixed_cam_width,
            nominal_height=self._fixed_cam_height,
            optical_centre_x=self._fixed_cx,
            optical_centre_y=self._fixed_cy,
            max_fov=self._fixed_ftheta_max_fov,
            polynomial=self._fixed_ftheta_poly)

        # 4. What the ROS consumer routes on. Passed verbatim into
        #    CameraInfo.distortion_model / .d by the bridge, so it must be the string
        #    mas_bearing_loc knows ("equidistant"), not Isaac's own "kannalaBrandt".
        camera.prim.CreateAttribute(
            "physicalDistortionModel", Sdf.ValueTypeNames.String).Set(
                self._fixed_distortion_model)
        camera.prim.CreateAttribute(
            "physicalDistortionCoefficients", Sdf.ValueTypeNames.FloatArray, False).Set(
                self._fixed_d)

        # 5. Read back. set_fisheye_polynomial_properties skips any coefficient that is
        #    falsy (`if polynomial[i]:`, camera.py:1267), so a coefficient that failed to
        #    author is a real possibility rather than a paranoid one.
        got_type = camera.get_projection_type()
        (n_w, n_h, o_cx, o_cy, max_fov, poly) = camera.get_fisheye_polynomial_properties()
        got_model = camera.prim.GetAttribute("physicalDistortionModel").Get()
        got_d = list(camera.prim.GetAttribute("physicalDistortionCoefficients").Get() or [])
        fx_published = (self._fixed_cam_width * camera.get_focal_length()
                        / camera.get_horizontal_aperture())

        problems = []
        if "fisheye" not in (got_type or ""):
            problems.append(f"projection type is {got_type!r}")
        if (n_w, n_h) != (self._fixed_cam_width, self._fixed_cam_height):
            problems.append(f"ftheta frame is {n_w}x{n_h}")
        if abs((o_cx or 0) - self._fixed_cx) > 1e-3 or abs((o_cy or 0) - self._fixed_cy) > 1e-3:
            problems.append(f"ftheta centre is ({o_cx}, {o_cy})")
        if max_fov is None or abs(max_fov - self._fixed_ftheta_max_fov) > 1e-2:
            problems.append(f"ftheta max_fov is {max_fov}")
        for i, want in enumerate(self._fixed_ftheta_poly):
            got = poly[i]
            if got is None or abs(got - want) > max(1e-12, abs(want) * 1e-5):
                problems.append(f"fthetaPoly{chr(ord('A') + i)} is {got!r}, wanted {want!r}")
        if got_model != self._fixed_distortion_model:
            problems.append(f"physicalDistortionModel is {got_model!r}")
        if len(got_d) != 4 or any(abs(a - b) > 1e-6 for a, b in zip(got_d, self._fixed_d)):
            problems.append(f"physicalDistortionCoefficients are {got_d}")
        if abs(fx_published - self._fixed_fx) > 0.1:
            problems.append(f"published fx would be {fx_published:.4f}, "
                            f"wanted {self._fixed_fx:.4f}")
        if problems:
            raise RuntimeError(
                "fisheye authoring readback FAILED on px4_%d: %s — refusing to boot a session "
                "whose camera is not the one it claims to be [MAS ticket 055]"
                % (vehicle_id, "; ".join(problems)))

        print("[PegasusApp] px4_%d FIXED FISHEYE: %dx%d, fx=%.4f px (published), "
              "cx/cy=%.1f/%.1f, maxFov=%.2f deg, model=%s — readback verified "
              "[MAS ticket 055]"
              % (vehicle_id, self._fixed_cam_width, self._fixed_cam_height, fx_published,
                 o_cx, o_cy, max_fov, got_model))

    def disable_vehicle_vehicle_collision(self, num_vehicles: int):
        """Author a SELF-FILTERING UsdPhysics.CollisionGroup over the vehicle prims.

        A collision group that lists ITSELF in `filteredGroups` means its members do not
        collide with one another, while collisions with everything OUTSIDE the group —
        notably the ground plane — are untouched. That is exactly the semantics RAL
        ticket 055 S21 needs: an interceptor may fly through the target to its true CPA,
        but a vehicle that falls still lands.

        Fail-closed by construction. A filter that silently fails to author is worse than
        no filter at all, because the cohort would look protected, run for 40 minutes and
        then lose a vehicle anyway — which is the failure this exists to prevent. So the
        prims are checked before authoring and the authored targets are read back after.

        Returns the READBACK-VERIFIED group description (path, filteredGroups, members) so
        the boot label reports what was authored rather than what was requested.
        """
        import omni.usd
        from pxr import Usd, UsdPhysics

        stage = omni.usd.get_context().get_stage()
        group_path = "/World/CollisionGroups/vehicles"
        group = UsdPhysics.CollisionGroup.Define(stage, group_path)

        # Self-filtering: members of this group ignore each other.
        filtered = group.CreateFilteredGroupsRel()
        filtered.AddTarget(group_path)

        # Membership. Newer USD exposes the collection through the schema; fall back to
        # the raw Usd.CollectionAPI instance name ("colliders") on older builds.
        try:
            includes = group.GetCollidersCollectionAPI().CreateIncludesRel()
        except Exception:
            includes = Usd.CollectionAPI.Apply(
                group.GetPrim(), "colliders").CreateIncludesRel()

        members = []
        for i in range(1, num_vehicles + 1):
            prim_path = "/World/" + self.namespace + str(i)
            if not stage.GetPrimAtPath(prim_path).IsValid():
                raise RuntimeError(
                    "DISABLE_VEHICLE_COLLISION: vehicle prim %s is missing — refusing to "
                    "boot with a filter that would silently not apply" % prim_path)
            includes.AddTarget(prim_path)
            members.append(prim_path)

        authored_filter = [t.pathString for t in filtered.GetTargets()]
        authored_members = [t.pathString for t in includes.GetTargets()]
        if group_path not in authored_filter or sorted(authored_members) != sorted(members):
            raise RuntimeError(
                "DISABLE_VEHICLE_COLLISION: readback mismatch — filteredGroups=%s "
                "includes=%s (expected self-filter on %s over %s)"
                % (authored_filter, authored_members, group_path, members))

        print("[PegasusApp] DISABLE_VEHICLE_COLLISION=1 -> self-filtering CollisionGroup "
              "%s over %d vehicles %s (vehicle-GROUND collision UNCHANGED) [RAL ticket 055]"
              % (group_path, len(members), members))

        return {"path": group_path,
                "filtered_groups": authored_filter,
                "members": authored_members,
                "ground_collision": "unchanged"}

    def write_boot_label(self, num_vehicles: int, nocollide_raw: str, collision_group):
        """Write the Isaac-side boot label — the machine-readable half of the boot witness.

        WHY. RAL ticket 055 `s21_deviation_deploy_assertion.md` §4: the collision regime,
        the single variable separating cohorts E58/E59 from E57/E56, is absent from the
        conductor's provenance entirely — "a reader of the provenance JSONs alone cannot
        distinguish E58 from E57" — because `experiment_conductor` has no visibility into
        THIS process's environment. Only Isaac knows the Isaac-side configuration, so
        Isaac writes it down. That ticket's filed follow-up is the conductor archiving
        this file into `boot_<id>_provenance.json`.

        It labels what was AUTHORED, not what was requested: `collision_group` is the
        readback-verified description returned by disable_vehicle_vehicle_collision(), so
        a filter that failed to apply cannot produce a label claiming it did.

        STALENESS is the hazard a well-known path invites — a consumer that reads a label
        left behind by a previous session would silently mis-label a whole cohort, which
        is the exact failure class this file exists to close. So the label carries this
        process's `pid` and `boot_unix_time`, and a consumer MUST check that `/proc/<pid>`
        is alive before trusting it (the conductor runs on this same box). The file is
        written atomically, so a reader never sees a half-written label.

        Fail-closed, like the filter above: if the label cannot be written the boot stops.
        A cohort that cannot state its own physics is the thing being prevented.
        """
        import hashlib
        import json
        import socket
        import time

        producer = os.path.abspath(__file__)
        try:
            with open(producer, "rb") as f:
                producer_sha256 = hashlib.sha256(f.read()).hexdigest()
        except OSError:
            producer_sha256 = None

        label = {
            "schema": "isaac_boot_label/1",
            # Liveness — a consumer must verify /proc/<pid> before trusting this file.
            "pid": os.getpid(),
            "boot_unix_time": time.time(),
            "hostname": socket.gethostname(),
            "producer": producer,
            "producer_sha256": producer_sha256,
            "headless": bool(args.headless),
            # The Isaac-side configuration surface that is invisible downstream.
            "num_vehicles": num_vehicles,
            "namespace": self.namespace,
            "camera_res": self._camera_res,
            "camera_width": self._cam_width,
            "camera_height": self._cam_height,
            "camera_vehicles": sorted(self._camera_ids),
            # MAS ticket 055 D2 — the fixed-fisheye selection, and the CONTRACT the ROS side
            # reads back. `gimbal_stabilizer/fixed_mount_publisher` refuses to start unless
            # its own namespace appears in `fixed_camera_vehicles`, which is what makes an
            # Isaac/ROS disagreement loud instead of silent. Consumers MUST check /proc/<pid>
            # is alive before trusting this file (see the docstring above).
            "fixed_camera_vehicles": sorted(self._fixed_camera_ids),
            "fixed_camera_vehicles_env": self._fixed_camera_env_raw,
            "fixed_camera": {
                "render_width": self._fixed_cam_width,
                "render_height": self._fixed_cam_height,
                "fx_px": self._fixed_fx,
                "cx_px": self._fixed_cx,
                "cy_px": self._fixed_cy,
                "projection_type": "fisheyePolynomial",
                "ftheta_poly_a_to_e": list(self._fixed_ftheta_poly),
                "ftheta_max_fov_deg": self._fixed_ftheta_max_fov,
                "horizontal_aperture_mm": self._fixed_h_aperture,
                "distortion_model": self._fixed_distortion_model,
                "distortion_coefficients": list(self._fixed_d),
                # The published frame is NOT what is rendered: sim_camera_relay applies the
                # 0.75 vertical squeeze. Recorded so a consumer of this label cannot mistake
                # the render frame for the frame the detector saw.
                "published_width": self._fixed_cam_width,
                "published_height": int(self._fixed_cam_height * 0.75),
                "published_fy_px": self._fixed_fx * 0.75,
                "relay_required": "sim_camera_relay/camera_relay",
            },
            "disable_vehicle_collision": collision_group is not None,
            # The raw env string as delivered ("" = unset, i.e. the default). The boolean
            # above is derived from the AUTHORED group and is the authoritative field.
            "disable_vehicle_collision_env": nocollide_raw,
            "collision_group": collision_group,
        }

        path = os.environ.get("ISAAC_BOOT_LABEL", "/tmp/isaac_boot_label.json").strip()
        tmp = path + ".%d.tmp" % os.getpid()
        try:
            with open(tmp, "w") as f:
                json.dump(label, f, indent=2, sort_keys=True)
                f.write("\n")
            os.replace(tmp, path)          # atomic: no reader sees a partial label
        except OSError as e:
            raise RuntimeError(
                "ISAAC_BOOT_LABEL: could not write the boot label to %s (%s) — refusing to "
                "boot a cohort that cannot state its own Isaac-side configuration "
                "[RAL ticket 055]" % (path, e))

        print("[PegasusApp] ISAAC_BOOT_LABEL -> %s (pid=%d, disable_vehicle_collision=%s) "
              "[RAL ticket 055]" % (path, label["pid"], label["disable_vehicle_collision"]))

    def load_flight_scene(self, usd_path: str, scale: float = 0.001, offset: tuple = (0.0, 0.0, 0.0)):
        """Load the Flight aesthetic scene USD with Y-up → Z-up rotation.

        Args:
            usd_path: Absolute path to the Flight USD file.
            scale: Uniform scale (USD is in cm with large coordinates; 0.001 fits the env).
            offset: (x, y, z) translation offset in meters after scaling.
        """
        import omni.usd
        from pxr import UsdGeom, Gf

        stage = omni.usd.get_context().get_stage()
        xform = UsdGeom.Xform.Define(stage, "/World/FlightScene")
        # Order: translate → rotate → scale (USD applies ops top-to-bottom)
        ox, oy, oz = offset
        xform.AddTranslateOp().Set(Gf.Vec3d(ox, oy, oz))
        xform.AddRotateXOp().Set(90.0)  # Y-up → Z-up
        xform.AddScaleOp().Set(Gf.Vec3f(scale, scale, scale))
        xform.GetPrim().GetReferences().AddReference(usd_path)

    def create_landmarks(self):
        from omni.isaac.core.objects import DynamicCuboid
        import numpy as np
        cube_1 = self.world.scene.add(
            DynamicCuboid(
                prim_path="/World/new_cube_1",
                name="cube_1",
                position=np.array([self.world_offset_x + 8.0, self.world_offset_y + 0, self.world_offset_z + 1.0]),
                scale=np.array([1.0, 1.0, 1.0]),
                size=1.0,
                color=np.array([255, 0, 0]),
            )
        )
        cube_2 = self.world.scene.add(
            DynamicCuboid(
                prim_path="/World/new_cube_2",
                name="cube_2",
                position=np.array([self.world_offset_x + 0.0, self.world_offset_y + 8.0, self.world_offset_z + 1.0]),
                scale=np.array([1.0, 1.0, 1.0]),
                size=1.0,
                color=np.array([0, 255, 0]),
            )
        )
        cube_3 = self.world.scene.add(
            DynamicCuboid(
                prim_path="/World/new_cube_3",
                name="cube_3",
                position=np.array([self.world_offset_x + 0, self.world_offset_y + 0, self.world_offset_z + 1.0]),
                scale=np.array([1.0, 1.0, 1.0]),
                size=1.0,
                color=np.array([0, 0, 255]),
            )
        )

    def vehicle_factory(self, vehicle_id: int, gap_x_axis: float):
        """Auxiliar method to create multiple multirotor vehicles

        Args:
            vehicle_id (_type_): _description_
        """

        # Create the vehicle
        # Try to spawn the selected robot in the world to the specified namespace
        config_multirotor = MultirotorConfig()
        # RAL ticket 019 revisit2 W0f: does this vehicle carry a camera at all?
        _has_camera = vehicle_id in self._camera_ids
        # MAS ticket 055 D2: and if so, is it the interceptor's fixed fisheye?
        _fixed_camera = vehicle_id in self._fixed_camera_ids

        # Create the multirotor configuration
        mavlink_config = PX4MavlinkBackendConfig({
            "vehicle_id": vehicle_id,
            "px4_autolaunch": True,
            "px4_dir": self.pg.px4_path,
            "px4_vehicle_model": self.pg.px4_default_airframe # CHANGE this line to 'iris' if using PX4 version bellow v1.14
        })
        config_multirotor.backends = [
            PX4MavlinkBackend(mavlink_config),
            ROS2Backend(vehicle_id=vehicle_id,
                        config={
                            "namespace": self.namespace,
                            "pub_sensors": True,
                            "pub_graphical_sensors": _has_camera,
                            "pub_state": True,
                            "sub_control": False,
                            # MAS ticket 055: the interceptor has no zoom hardware, and
                            # MonocularCamera.set_zoom would rebuild the focal length from
                            # mean(fx, fy) using a hardcoded 3 um pixel size — overwriting
                            # the aperture that carries fx. `fixed_mount_publisher` does not
                            # publish camera/zoom_level_cmd, so nothing should arrive; this
                            # closes the door rather than trusting that.
                            "sub_zoom": not _fixed_camera,
                        })]

        # RAL ticket 019 revisit2 W0f: skip the render product entirely for vehicles that have
        # no camera consumer (see CAMERA_VEHICLES above). An empty graphical_sensors list is
        # safe by construction — the post-world.reset() property loop iterates
        # `vehicle._graphical_sensors` and simply does nothing — and the USD prim is untouched.
        if _has_camera and _fixed_camera:
            # MAS ticket 055. The 3x3 `intrinsics` here only seeds MonocularCamera.set_zoom
            # (which this vehicle has disabled) — the real lens is authored on the prim
            # after world.reset() by author_fisheye_camera(). It is still given the correct
            # ISOTROPIC matrix so that, if zoom is ever re-enabled by mistake, set_zoom's
            # mean(fx, fy) reconstruction is a no-op rather than a silent 444.76 -> 388.87
            # miscalibration.
            config_multirotor.graphical_sensors = [
                MonocularCamera("/pitch_link/camera",
                config={
                    "frequency": 25,
                    "resolution": (self._fixed_cam_width, self._fixed_cam_height),
                    "position": np.array([0, 0, 0]),
                    "orientation": np.array([0.0, 0.0, 0.0]),
                    "intrinsics": np.array([[self._fixed_fx, 0, self._fixed_cx],
                                            [0, self._fixed_fx, self._fixed_cy],
                                            [0, 0, 1]]),
                    }
                )
            ]
        elif _has_camera:
            config_multirotor.graphical_sensors = [
                MonocularCamera("/pitch_link/camera",
                config={
                    "frequency": 25,
                    "resolution": (self._cam_width, self._cam_height),
                    "position": np.array([0, 0, 0]),
                    "orientation": np.array([0.0, 0.0, 0.0]),
                    "intrinsics": np.array(self._cam_matrix),
                    }
                )
            ]
        else:
            config_multirotor.graphical_sensors = []
            print(f"[PegasusApp] vehicle {vehicle_id}: camera SKIPPED (not in CAMERA_VEHICLES)")

        vehicle_name = self.namespace + str(vehicle_id)
        vehicle_stage_path = "/World/" + vehicle_name
        # vehicle_stage_path = "/World/quadrotor"


        vehicle = Multirotor(
            vehicle_stage_path,
            # ROBOTS['Iris'],
            ROBOTS['IrisGimbal3'],
            vehicle_id,
            [self.world_offset_x + gap_x_axis * (vehicle_id+1), self.world_offset_y + gap_x_axis * (vehicle_id+1), self.world_offset_z + 2.0],
            Rotation.from_euler("XYZ", [0.0, 0.0, 3.14], degrees=True).as_quat(),
            config=config_multirotor)
        self.vehicles += [vehicle]
        # MAS ticket 055: the post-reset camera loop has to know which vehicle a sensor
        # belongs to in order to pick fisheye vs pinhole, and Vehicle exposes only
        # `_vehicle_name` / `_stage_prefix`, not the id it was constructed with.
        self._vehicle_by_id[vehicle_id] = vehicle
        asyncio.ensure_future(self.create_ros_action_graph(vehicle_stage_path, vehicle_name))
        # asyncio.ensure_future(self.create_ros_camera_graph(vehicle_stage_path, vehicle_name))

    async def create_ros_camera_graph(self, vehicle_stage_path, vehicle_name):
        try:
            await omni.kit.app.get_app().next_update_async()
            camera_graph = bridge.Ros2CameraGraph()
            camera_graph._og_path = vehicle_stage_path + "/CameraGraph"
            camera_graph._camera_prim = vehicle_name + "/pitch_link/camera"
            camera_graph._node_namespace = vehicle_name
            camera_graph.make_graph()
        except Exception as e:
            print(e)
        pass

    async def create_simulation_time_graph(self):
        try:
            await omni.kit.app.get_app().next_update_async()
            og.Controller.edit(
                {"graph_path": "/World/SimulationTimeGraph", "evaluator_name": "execution"},
                {
                    og.Controller.Keys.CREATE_NODES: [
                        ("Context", "isaacsim.ros2.bridge.ROS2Context"),
                        ("OnPlaybackTick", "omni.graph.action.OnPlaybackTick"),
                        ("ReadSimTime", "isaacsim.core.nodes.IsaacReadSimulationTime"),
                        ("PublishClock", "isaacsim.ros2.bridge.ROS2PublishClock"),
                    ],
                    og.Controller.Keys.CONNECT: [
                        ("OnPlaybackTick.outputs:tick", "PublishClock.inputs:execIn"),
                        ("Context.outputs:context", "PublishClock.inputs:context"),
                        ("ReadSimTime.outputs:simulationTime", "PublishClock.inputs:timeStamp"),
                    ],
                    og.Controller.Keys.SET_VALUES: [
                        ("PublishClock.inputs:topicName", "/clock"),
                    ],
                },
            )
            await omni.kit.app.get_app().next_update_async()
        except Exception as e:
            print(e)
        pass


    async def create_ros_action_graph(self, vehicle_stage_path, vehicle_name):
        try:
            await omni.kit.app.get_app().next_update_async()
            og.Controller.edit(
                {"graph_path": vehicle_stage_path + "/ActionGraph", "evaluator_name": "execution"},
                {
                    og.Controller.Keys.CREATE_NODES: [
                        ("OnPlaybackTick", "omni.graph.action.OnPlaybackTick"),
                        ("ReadSimTime", "isaacsim.core.nodes.IsaacReadSimulationTime"),
                        ("Context", "isaacsim.ros2.bridge.ROS2Context"),
                        ("PublishJointState", "isaacsim.ros2.bridge.ROS2PublishJointState"),
                        ("SubscribeJointState", "isaacsim.ros2.bridge.ROS2SubscribeJointState"),
                        ("ArticulationController", "isaacsim.core.nodes.IsaacArticulationController"),
                    ],
                    og.Controller.Keys.CONNECT: [
                        ("OnPlaybackTick.outputs:tick", "PublishJointState.inputs:execIn"),
                        ("OnPlaybackTick.outputs:tick", "SubscribeJointState.inputs:execIn"),
                        ("OnPlaybackTick.outputs:tick", "ArticulationController.inputs:execIn"),
                        ("Context.outputs:context", "PublishJointState.inputs:context"),
                        ("Context.outputs:context", "SubscribeJointState.inputs:context"),
                        ("ReadSimTime.outputs:simulationTime", "PublishJointState.inputs:timeStamp"),
                        ("SubscribeJointState.outputs:jointNames", "ArticulationController.inputs:jointNames"),
                        (
                            "SubscribeJointState.outputs:positionCommand",
                            "ArticulationController.inputs:positionCommand",
                        ),
                        (
                            "SubscribeJointState.outputs:velocityCommand",
                            "ArticulationController.inputs:velocityCommand",
                        ),
                        ("SubscribeJointState.outputs:effortCommand", "ArticulationController.inputs:effortCommand"),
                    ],
                    og.Controller.Keys.SET_VALUES: [
                        # Setting the /Franka target prim to Articulation Controller node
                        ("ArticulationController.inputs:robotPath", vehicle_stage_path + "/body"),
                        ("PublishJointState.inputs:topicName", vehicle_name + "/isaac_joint_states"),
                        ("SubscribeJointState.inputs:topicName", vehicle_name + "/isaac_joint_commands"),
                        ("PublishJointState.inputs:targetPrim", [vehicle_stage_path + "/body"]),
                    ],
                },
            )
            await omni.kit.app.get_app().next_update_async()
        except Exception as e:
            print(e)
        pass

    def run(self):
        """
        Method that implements the application main loop, where the physics steps are executed.
        """

        # Start the simulation
        self.timeline.play()

        # The "infinite" loop
        while simulation_app.is_running() and not self.stop_sim:

            # Update the UI of the app and perform the physics step
            self.world.step(render=True)

        # Cleanup and stop
        carb.log_warn("PegasusApp Simulation App is closing.")
        self.timeline.stop()
        simulation_app.close()

def main():

    # Instantiate the template app
    pg_app = PegasusApp()

    # Run the application loop
    pg_app.run()

if __name__ == "__main__":
    main()
